/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-125084-geb7f4b4e79-20260617"
#endif /* AVUTIL_FFVERSION_H */
